"""
Router for GET /portfolio/weights and GET /portfolio/frontier.

Returns optimized portfolio weights and efficient frontier data points
from the most recent pipeline run.
"""
from __future__ import annotations

from typing import Optional

import numpy as np
import pandas as pd
from fastapi import APIRouter, HTTPException, Query

from src.api.deps import equity_curve_path, predictions_path, resolve_run, returns_path, weights_path
from src.pipeline.registry import load_run_manifest
from src.api.schemas.responses import (
    EquityCurvePoint,
    EquityCurveResponse,
    FrontierPoint,
    FrontierResponse,
    PortfolioWeightsResponse,
    WeightItem,
)
from src.optimization.markowitz import (
    portfolio_return,
    portfolio_volatility,
    solve_markowitz,
)
from src.utils.config_loader import get_config

router = APIRouter(prefix="/portfolio", tags=["portfolio"])

_FRONTIER_POINTS = 50  # number of lambda samples for efficient frontier


@router.get(
    "/weights",
    response_model=PortfolioWeightsResponse,
    summary="Retrieve optimized portfolio weights",
)
def get_weights(
    run_id: Optional[str] = Query(
        default=None,
        description="Run ID to retrieve weights from. Defaults to the latest completed run.",
    ),
) -> PortfolioWeightsResponse:
    """Return the Sharpe-maximizing portfolio weights for a given run.

    Weights are stored by stage_export_artifacts as a CSV under artifacts/weights/.
    Each weight is in [0, 1] and all weights sum to 1 (no short selling).

    Raises:
        404: If no completed runs exist or the artifact is missing.
    """
    try:
        resolved_id, model = resolve_run(run_id)
    except (LookupError, FileNotFoundError) as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    path = weights_path(resolved_id, model)
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Weights artifact not found for run_id='{resolved_id}'. "
                   "Ensure the pipeline ran successfully through stage_export_artifacts.",
        )

    df = pd.read_csv(path)
    items = [
        WeightItem(ticker=row["Ticker"], weight=float(row["Weight"]))
        for _, row in df.iterrows()
    ]

    return PortfolioWeightsResponse(run_id=resolved_id, model=model, weights=items)


@router.get(
    "/frontier",
    response_model=FrontierResponse,
    summary="Retrieve efficient frontier data",
)
def get_frontier(
    run_id: Optional[str] = Query(
        default=None,
        description="Run ID to compute frontier from. Defaults to the latest completed run.",
    ),
    n_points: int = Query(
        default=_FRONTIER_POINTS,
        ge=10,
        le=200,
        description="Number of frontier points to sample (lambda values from 0 to 1).",
    ),
) -> FrontierResponse:
    """Compute and return the efficient frontier for a given run.

    The frontier is generated by sweeping `lambda` from 0 (maximum return) to 1
    (minimum volatility) and solving the Markowitz objective for each value.
    Expected returns and the covariance matrix are derived from the run artifacts.

    Args:
        run_id: Optional run identifier.
        n_points: Number of lambda values to sample.

    Raises:
        404: If no completed runs exist or required artifacts are missing.
    """
    try:
        resolved_id, model = resolve_run(run_id)
    except (LookupError, FileNotFoundError) as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    preds_path = predictions_path(resolved_id, model)
    ret_path = returns_path(resolved_id)

    for path in (preds_path, ret_path):
        if not path.exists():
            raise HTTPException(
                status_code=404,
                detail=f"Artifact not found: {path}. "
                       "Ensure the pipeline ran through stage_export_artifacts.",
            )

    # Load blended mu and returns
    preds_df = pd.read_csv(preds_path)
    mu = preds_df.set_index("Ticker")["Predicted_Return"].values.astype(float)

    returns_df = pd.read_csv(ret_path, index_col=0, parse_dates=True)
    cov = returns_df.cov().values.astype(float)

    # Risk-free rate from config (period-adjusted: monthly)
    pipeline_cfg = get_config("pipeline")
    rf_annual: float = pipeline_cfg["optimization"]["risk_free_rate"]
    freq: str = pipeline_cfg["optimization"].get("frequency", "monthly")
    _periods_map = {"daily": 252, "weekly": 52, "monthly": 12, "annually": 1}
    periods: int = _periods_map.get(freq, 12)
    rf_period: float = (1 + rf_annual) ** (1 / periods) - 1

    lambdas = np.linspace(0.0, 1.0, n_points)
    points: list[FrontierPoint] = []

    for lam in lambdas:
        w = solve_markowitz(mu, cov, lamb=float(lam))
        if w is None:
            continue
        ret = float(portfolio_return(w, mu))
        vol = float(portfolio_volatility(w, cov))
        sharpe = (ret - rf_period) / vol if vol > 0 else 0.0
        points.append(
            FrontierPoint(
                lambda_param=round(float(lam), 4),
                volatility=round(vol, 6),
                expected_return=round(ret, 6),
                sharpe=round(sharpe, 4),
            )
        )

    return FrontierResponse(
        run_id=resolved_id,
        risk_free_rate=rf_annual,
        n_points=len(points),
        points=points,
    )


@router.get(
    "/equity-curve",
    response_model=EquityCurveResponse,
    summary="Retrieve portfolio equity curve over the out-of-sample test period",
)
def get_equity_curve(
    run_id: Optional[str] = Query(
        default=None,
        description="Run ID to retrieve equity curve from. Defaults to the latest completed run.",
    ),
) -> EquityCurveResponse:
    """Return the portfolio cumulative return series over the out-of-sample test period.

    The equity curve starts at the first test period (value = 1 + r_1) and compounds
    forward. A value of 1.5 means the portfolio gained 50% since the start of the test
    period.

    Raises:
        404: If no completed runs exist or the equity curve artifact is missing.
             Re-run the pipeline to generate the artifact.
    """
    try:
        resolved_id, model = resolve_run(run_id)
    except (LookupError, FileNotFoundError) as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    ec_path = equity_curve_path(resolved_id, model)

    if ec_path.exists():
        df = pd.read_csv(ec_path)
    else:
        # Fallback: compute on-the-fly from existing artifacts.
        # The walk-forward test period is a contiguous slice:
        #   test_start = lag_window + int((n_returns - lag_window) * train_ratio)
        ret_path = returns_path(resolved_id)
        w_path = weights_path(resolved_id, model)
        for p in (ret_path, w_path):
            if not p.exists():
                raise HTTPException(
                    status_code=404,
                    detail=f"Artifact not found: {p}. Ensure the pipeline ran successfully.",
                )

        returns_df = pd.read_csv(ret_path, index_col=0, parse_dates=True)
        weights_df = pd.read_csv(w_path)
        manifest = load_run_manifest(resolved_id)
        pcfg = manifest.get("pipeline_cfg", {})
        lag_window: int = pcfg.get("features", {}).get("lag_window", 24)
        train_ratio: float = pcfg.get("models", {}).get("train_ratio", 0.7)

        n = len(returns_df)
        test_start = lag_window + int((n - lag_window) * train_ratio)
        test_returns = returns_df.iloc[test_start:]

        weights_s = weights_df.set_index("Ticker")["Weight"]
        common = weights_s.index.intersection(test_returns.columns)
        portfolio_returns = test_returns[common].dot(weights_s[common].values)

        equity = (1 + portfolio_returns).cumprod()
        df = pd.DataFrame({"date": equity.index.astype(str), "cumulative_return": equity.values})

    points = [
        EquityCurvePoint(date=str(row["date"]), cumulative_return=float(row["cumulative_return"]))
        for _, row in df.iterrows()
    ]
    return EquityCurveResponse(
        run_id=resolved_id,
        model=model,
        period_start=str(df["date"].iloc[0]),
        period_end=str(df["date"].iloc[-1]),
        n_points=len(points),
        points=points,
    )
