"""
Router for GET /portfolio/weights and GET /portfolio/frontier.

Returns optimized portfolio weights and efficient frontier data points
from the most recent pipeline run.
"""
from __future__ import annotations

from typing import Optional

import numpy as np
import pandas as pd
from fastapi import APIRouter, HTTPException, Query

from src.api.deps import predictions_path, resolve_run, returns_path, weights_path
from src.api.schemas.responses import (
    FrontierPoint,
    FrontierResponse,
    PortfolioWeightsResponse,
    WeightItem,
)
from src.optimization.markowitz import (
    portfolio_return,
    portfolio_volatility,
    solve_markowitz,
)
from src.utils.config_loader import get_config

router = APIRouter(prefix="/portfolio", tags=["portfolio"])

_FRONTIER_POINTS = 50  # number of lambda samples for efficient frontier


@router.get(
    "/weights",
    response_model=PortfolioWeightsResponse,
    summary="Retrieve optimized portfolio weights",
)
def get_weights(
    run_id: Optional[str] = Query(
        default=None,
        description="Run ID to retrieve weights from. Defaults to the latest completed run.",
    ),
) -> PortfolioWeightsResponse:
    """Return the Sharpe-maximizing portfolio weights for a given run.

    Weights are stored by stage_export_artifacts as a CSV under artifacts/weights/.
    Each weight is in [0, 1] and all weights sum to 1 (no short selling).

    Raises:
        404: If no completed runs exist or the artifact is missing.
    """
    try:
        resolved_id, model = resolve_run(run_id)
    except (LookupError, FileNotFoundError) as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    path = weights_path(resolved_id, model)
    if not path.exists():
        raise HTTPException(
            status_code=404,
            detail=f"Weights artifact not found for run_id='{resolved_id}'. "
                   "Ensure the pipeline ran successfully through stage_export_artifacts.",
        )

    df = pd.read_csv(path)
    items = [
        WeightItem(ticker=row["Ticker"], weight=float(row["Weight"]))
        for _, row in df.iterrows()
    ]

    return PortfolioWeightsResponse(run_id=resolved_id, model=model, weights=items)


@router.get(
    "/frontier",
    response_model=FrontierResponse,
    summary="Retrieve efficient frontier data",
)
def get_frontier(
    run_id: Optional[str] = Query(
        default=None,
        description="Run ID to compute frontier from. Defaults to the latest completed run.",
    ),
    n_points: int = Query(
        default=_FRONTIER_POINTS,
        ge=10,
        le=200,
        description="Number of frontier points to sample (lambda values from 0 to 1).",
    ),
) -> FrontierResponse:
    """Compute and return the efficient frontier for a given run.

    The frontier is generated by sweeping `lambda` from 0 (maximum return) to 1
    (minimum volatility) and solving the Markowitz objective for each value.
    Expected returns and the covariance matrix are derived from the run artifacts.

    Args:
        run_id: Optional run identifier.
        n_points: Number of lambda values to sample.

    Raises:
        404: If no completed runs exist or required artifacts are missing.
    """
    try:
        resolved_id, model = resolve_run(run_id)
    except (LookupError, FileNotFoundError) as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    preds_path = predictions_path(resolved_id, model)
    ret_path = returns_path(resolved_id)

    for path in (preds_path, ret_path):
        if not path.exists():
            raise HTTPException(
                status_code=404,
                detail=f"Artifact not found: {path}. "
                       "Ensure the pipeline ran through stage_export_artifacts.",
            )

    # Load blended mu and returns
    preds_df = pd.read_csv(preds_path)
    mu = preds_df.set_index("Ticker")["Predicted_Return"].values.astype(float)

    returns_df = pd.read_csv(ret_path, index_col=0, parse_dates=True)
    cov = returns_df.cov().values.astype(float)

    # Risk-free rate from config (period-adjusted: monthly)
    pipeline_cfg = get_config("pipeline")
    rf_annual: float = pipeline_cfg["optimization"]["risk_free_rate"]
    freq: str = pipeline_cfg["optimization"].get("frequency", "monthly")
    _periods_map = {"daily": 252, "weekly": 52, "monthly": 12, "annually": 1}
    periods: int = _periods_map.get(freq, 12)
    rf_period: float = (1 + rf_annual) ** (1 / periods) - 1

    lambdas = np.linspace(0.0, 1.0, n_points)
    points: list[FrontierPoint] = []

    for lam in lambdas:
        w = solve_markowitz(mu, cov, lamb=float(lam))
        if w is None:
            continue
        ret = float(portfolio_return(w, mu))
        vol = float(portfolio_volatility(w, cov))
        sharpe = (ret - rf_period) / vol if vol > 0 else 0.0
        points.append(
            FrontierPoint(
                lambda_param=round(float(lam), 4),
                volatility=round(vol, 6),
                expected_return=round(ret, 6),
                sharpe=round(sharpe, 4),
            )
        )

    return FrontierResponse(
        run_id=resolved_id,
        risk_free_rate=rf_annual,
        n_points=len(points),
        points=points,
    )
